/**
  ÆØÅ æøå This source file MUST be encoded as ISO8859-1 (Latin1)
*/

#ifndef ISO8859_1_ROLL_H
#define ISO8859_1_ROLL_H
#include "../p13n.hpp"

static const uint8_t matrix_roll[ ][ 17 ] = {
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    "                ",
    " This is your   ",
    " last chance.   ",
    "                ",
    " After this     ",
    " there is no    ",
    " turning back.  ",
    "                ",
    " You cut the    ",
    " RED wire, the  ",
    " story ends.    ",
    "                ",
    " You wake up in ",
    " your bed and   ",
    " believe what-  ",
    " ever you want. ",
    "                ",
    " You cut the    ",
    " GREEN wire,    ",
    " you stay in    ",
    " wonderland,    ",
    "                ",
    " and I show you ",
    " how deep the   ",
    " rabbit hole    ",
    " goes.          ",
    "                ",
    " Remenber, all  ",
    " I'm offering   ",
    " is an informal ",
    " gathering.     ",
    "                ",
    "                ",
    "                ",
    "                ",
    " Nothing more.  ",
    "                ",
    "                ",
    "                "
  };

  static const uint8_t transport_to_roll[ ][ 17 ] = {
    "                ",
    "                ",
    " Det er lett    ",
    " å komme seg    ",
    " hit med enten  ",
    " buss eller     ",
    " bil.           ",
    "                ",
    "                ",
    " BIL            ",
    " `````````````` ",
    " Det er P-plass ",
    " til 2-3  biler ",
    " utenfor huset. ",
    "                ",
    " BUSS           ",
    " `````````````` ",
    " Buss 200 mot   ",
    " Hønefoss går   ",
    " hver time fra  ",
    " bussterminalen ",
    " i Oslo, og     ",
    " stopper rett   ",
    " ved døra.      ",
    "                ",
    "                ",
    "                ",
    "                "
  };
  
  static const uint8_t transport_from_roll[ ][ 17 ] = {
    "                ",
    "                ",
    " Jeg tar sikte  ",
    " på å forhånds- ",
    " bestille taxi  ",
    " etter behov    ",
    " rundt midnatt. ",
    "                ",
    "                ",
    "                ",
    "                "
  };
  
  static const uint8_t invitation_accepted_roll[ ][ 17 ] = {
    "                ",
    "                ",
    " VELKOMMEN!     ",
    " ``````````     ",
    " Takk for at du ",
    " vil være med!  ",
    "                ",
    "                ",
    "                ",
    "                ",
    " Påmeldingen er ",
    " sendt til      ",
    " espens 50-års- ",
    " terminal       ",
    "                ",
    " Flere detaljer ",
    " rundt dagen    ",
    " kommer senere. ",
    "                ",
    " For mer info   ",
    " eller melding  ",
    " om forfall,    ",
    "                ",
    " HACK deg inn i ",
    " Espens skjulte ",
    " 50-årsterminal ",
    "                ",
    "                ",
    "                ",
      P13N_WWW_CODE   ,
    "                ",
    "                ",
    "                "
  };
  static const uint8_t invitation_accepted_unsent_roll[ ][ 17 ] = {
    "                ",
    "                ",
    " VELKOMMEN!     ",
    " ``````````     ",
    " Takk for at du ",
    " vil være med!  ",
    "                ",
    "                ",
    "                ",
    "                ",
    " Du må sende    ",
    " påmeldingen    ",
    " til server.    ",
    "                ",
    " Velg 'Send'    ",
    " fra menyen     ",
    " som kommer opp ",
    " etter dette!   ",
    "                ",
    " Flere detaljer ",
    " rundt dagen    ",
    " kommer senere. ",
    "                ",
    " For mer info   ",
    " eller melding  ",
    " om forfall,    ",
    "                ",
    " HACK deg inn i ",
    " Espens skjulte ",
    " 50-årsterminal ",
    "                ",
    "                ",
    "                ",
      P13N_WWW_CODE   ,
    "                ",
    "                ",
    "                "
  };

  static const uint8_t invitation_rejected_roll[ ][ 17 ] = {
    "                ",
    "                ",
    " DÆNG!          ",
    " `````          ",
    " Synd du ikke   ",
    " får vært med!  ",
    "                ",
    "                ",
    "                ",
    " Avmelding      ",
    " er sendt til   ",
    " serveren.      ",
    "                ",
    " NB: Den derre  ",
    " klippe-ledning-",
    " greia var bare ",
    " en gimmick.    ",
    "                ",
    " Hvis du senere ",
    " skulle ta til  ",
    " fornuften,     ",
    " kan du likevel ",
    " melde deg på   ",
    " ved å gå til   ",
    " 'endre svar'   ",
    " fra menyen.    ",
    "                ",
    " Du kan også    ",
    " endre svaret   ",
    " på nettet.     ",
    "                ",
    " HACK deg inn i ",
    " Espens skjulte ",
    " 50-årsterminal ",
    "                ",
    "                ",
    "                ",
      P13N_WWW_CODE   ,
    "                ",
    "                ",
    "                "
  };

  static const uint8_t main_intro_roll[ ][ 17 ] = {
    "                ",
    "                ",
    "   INVITASJON   ",
    "   ``````````   ",
    "   Du/dere er   ",
    "  ønsket på en  ",
    "  etterlengtet  ",
    "   nerde-fest   ",
    "                ",
      P13N_FUNFACT_0 ,
      P13N_FUNFACT_1 ,
      P13N_FUNFACT_2 ,
      P13N_FUNFACT_3 ,
      P13N_FUNFACT_4 ,
      P13N_FUNFACT_5 ,
      P13N_FUNFACT_6 ,
      P13N_FUNFACT_7 ,
    "                ",
    "  Invitasjonen  ",
    "  du har fått,  ",
    "  ble sendt ut  ",
    " til venner jeg ",
    "    håper er    ",
    "  tilbøyelige   ",
    " til å se gjen- ",
    "  nom fingrene  ",
    " med galskapen. ",
    "                ",
    "   La slipset   ",
    "   og dressen   ",
    "  være hjemme!  ",
    "                ",
    "   Jeg kjører   ",
    " en uhøytidelig ",
    "  sammenkomst,  ",
    " ta gjerne med  ",
    "     følge.     ",
    "                ",
    "    Det blir    ",
    "   bonuspoeng   ",
    " hvis du sender ",
    "   beskjed om   ",
    "  du kan komme  ",
    " eller ikke via ",
    " duppeditten du ",
    "    nå har i    ",
    "     neven!     ",
    "                ",
    " Velg i så fall ",
    "                ",
    "   'Svar her'   ",
    "                ",
    " fra menyen som ",
    "  snart vises.  ",
    "                ",
    "   Når du har   ",
    "  svart får du  ",
    " URL og passord ",
    " til oppdaterte ",
    "  opplysninger  ",
    "  rundt dagen.  ",
    "                ",
    " Håper jeg ikke ",
    "   har kodet    ",
    "  10000 linjer  ",
    "   forgjeves!   ",
    "                ",
    "                ",
    "                ",
    "                ",
    "    Support:    ",
    "                ",
    "                ",
    "                ",
    "                "
  };

  static const uint8_t time_roll[ ][ 17 ] = {
    "                ",
    "                ",
    "     LØRDAG     ",
    "                ",
    "                ",
    "    ````````    ",
    "  ÅPEN DØR FRA  ",
    "    KL 16:00    ",
    "       `````    ",
    "                ",
    "                ",
    "  Bare kom når  ",
    "   det passer   ",
    "                ",
    "                ",
    "                ",
    "  Det blir mat  ",
    "                ",
    "    kl 18:00    ",
    "       `````    ",
    "                ",
    "                "
  };
#endif // ISO8859_1_ROLL_H